# Generated by Django 5.2.12 on 2026-03-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
    ]
