# Generated by Django 5.2.12 on 2026-03-10 21:56

import eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_table_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to=eventos.models.media_upload_path),
        ),
    ]
